version: "3.5"

services:
    db:
      image: postgres:12
      container_name: chat-db
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=pass
        - POSTGRES_DB=chat-db
      volumes:
        - db-data:/var/lib/postgresql/data
      networks:
        - chat-net

    api:
      build: .
      container_name: chat-api
      ports:
        - 9000:9000
      networks:
        - chat-net
      depends_on:
        - db
volumes:
  db-data:
    name: chat-data
networks:
  chat-net:
    name: chat

